version: '3'

volumes:
  web:
    driver: local

services:
################################
#   Setup node container
################################
  server:
    image: node:8.0.0
    ports:
      - 3000:3000
    #environment:
      #SERVER_NAME: ""
    volumes:
      - .:/reactweb
    stdin_open: true
    tty: true
    command: "/bin/sh -c 'cd /reactweb && npm start'"
  bash:
    image: node:8.0.0
    volumes:
      - .:/reactweb
    stdin_open: true
    tty: true
    command: /bin/sh
