export const GET_PHOTOS = "LOAD_PHOTOS";
export const GET_PHOTOS_SUCCESS = "LOAD_PHOTOS_SUCCESS";
export const GET_PHOTOS_NOT_FOUND = "LOAD_PHOTOS_NOT_FOUND";
export const GET_PHOTOS_FAIL = "LOAD_PHOTOS_FAIL";

export const GET_ARTICLE = "LOAD_ARTICLE";
export const GET_ARTICLE_SUCCESS = "LOAD_ARTICLE_SUCCESS";
export const GET_ARTICLE_NOT_FOUND = "LOAD_ARTICLE_NOT_FOUND";
export const GET_ARTICLE_FAIL = "LOAD_ARTICLE_FAIL";
