FROM node:8.0.0
MAINTAINER sampahcoding anasyarifah@gmail.com

# Create app directory
RUN mkdir -p /reactweb
WORKDIR /reactweb

EXPOSE 3000

#COPY package.json .
#RUN npm i --no-optional && npm dedupe
